// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXSfkWkz6qK-7ZpTDEOEnFGF7IF520q04',
    appId: '1:1045437845196:web:c143512f8e7782114a7c69',
    messagingSenderId: '1045437845196',
    projectId: 'sports-app-959f9',
    authDomain: 'sports-app-959f9.firebaseapp.com',
    storageBucket: 'sports-app-959f9.appspot.com',
    measurementId: 'G-WZS1R27CK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNNeHS8W_b3zt1VF60oN10ySm9zlcYd0',
    appId: '1:1045437845196:android:99c3e79bec33fc0e4a7c69',
    messagingSenderId: '1045437845196',
    projectId: 'sports-app-959f9',
    storageBucket: 'sports-app-959f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnAa90Y0hKtwpakow4apDQncFtT4qdOdU',
    appId: '1:1045437845196:ios:88660da4922109604a7c69',
    messagingSenderId: '1045437845196',
    projectId: 'sports-app-959f9',
    storageBucket: 'sports-app-959f9.appspot.com',
    iosClientId: '1045437845196-sauu93o4cafmgtcabla2216uvco9qaf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsApp',
  );
}
